-- psql -d resources -f server/db/seed.sql

\c resources 

INSERT INTO resources(title, logo, website, doc, pub, keywords, citations, pmid, altmetric, github, youtube, parameter, category) VALUES
('Geneshot', 'http://labs.icahn.mssm.edu/maayanlab/wp-content/uploads/sites/75/2019/05/geneshot_logo-3.jpg', 'https://amp.pharm.mssm.edu/geneshot/index.html
', 'https://amp.pharm.mssm.edu/geneshot/help.html', 'https://academic.oup.com/nar/article/47/W1/W571/5494749
', 'search engine, RNA-seq, genomics, gene set, similarity matrix, text mining, matrix, visualization
', 26, 31114885, 20, 'https://github.com/MaayanLab/geneshot', 'https://www.youtube.com/watch?v=mp1OYsFHBd0', 'geneshot', 'RNA-seq'),
('BioJupies', 'http://labs.icahn.mssm.edu/maayanlab/wp-content/uploads/sites/75/2018/08/biojupies-300x99.jpg', 'https://amp.pharm.mssm.edu/biojupies/', 'https://amp.pharm.mssm.edu/biojupies/help', 'https://www.ncbi.nlm.nih.gov/pubmed/30447998', 'RNA-seq, Jupyter notebooks, enrichment analysis, heat maps, differential expression, visualization, cloud storage, LINCS', 58, 30447998, 113, 'https://github.com/MaayanLab/biojupies', 'https://www.youtube.com/watch?v=KMIrW3wb690', 'biojupies', 'RNA-seq'),
('Archs4', 'http://labs.icahn.mssm.edu/maayanlab/wp-content/uploads/sites/75/2017/04/archs4_icon-150x150.png','https://amp.pharm.mssm.edu/archs4/', 'https://amp.pharm.mssm.edu/archs4/help.html', 'https://www.ncbi.nlm.nih.gov/pubmed/29636450', 'RNA-seq, protein-protein interactions, visualization, gene expression, LINCS', 49, 29636450, 174, 'https://github.com/MaayanLab/archs4', 'https://www.youtube.com/watch?v=xw8vh_sYJ4s', 'archs4', 'RNA-seq'),
('Genes2FANS', 'http://labs.icahn.mssm.edu/maayanlab/wp-content/uploads/sites/75/2014/10/G2F-icon.png', '', '', 'https://www.ncbi.nlm.nih.gov/pubmed/22748121', 'networks, proteomics, database, protein-protein interaction, gene set libraries', 52, 22748121, 4, '', '', 'genes2fans', 'proteomics'),
('Sets2Networks', 'http://labs.icahn.mssm.edu/maayanlab/wp-content/uploads/sites/75/2014/10/S2N-icon.png', 'https://www.maayanlab.net/S2N/', '', 'https://www.ncbi.nlm.nih.gov/pubmed/22824380', 'networks, protein-protein interaction, proteomics', 33, 22824380, 1, '', 'https://www.youtube.com/watch?v=h7Iy-hpZJ7o', 'sets2networks', 'proteomics'),
('ESCAPE', 'http://labs.icahn.mssm.edu/maayanlab/wp-content/uploads/sites/75/2014/10/ESCAPE-icon.png', '', '', 'https://www.ncbi.nlm.nih.gov/pubmed/23794736', 'database, proteomics, visualization, networks', 26, 23794736, 9, '','', 'escape', 'proteomics'),
('L1000FWD', 'http://labs.icahn.mssm.edu/maayanlab/wp-content/uploads/sites/75/2014/10/L1000FWD_logo-150x150.png', 'https://amp.pharm.mssm.edu/L1000FWD/', 'https://amp.pharm.mssm.edu/datasets2tools/help', 'https://www.ncbi.nlm.nih.gov/pubmed/29485625', 'database, datasets, canned analyses, interoperability, LINCS', 17, 29420694, 12, 'https://github.com/MaayanLab/L1000FWD', 'https://www.youtube.com/watch?v=vU43FfqMd0o', 'l1000fwd', 'visualization'),
('Clustergrammer', 'http://labs.icahn.mssm.edu/maayanlab/wp-content/uploads/sites/75/2018/08/clustergrammer_logo-300x55.png', 'https://amp.pharm.mssm.edu/clustergrammer/', 'https://clustergrammer.readthedocs.io/', 'https://www.ncbi.nlm.nih.gov/pubmed/28994825', 'visualization, matrix, heatmap, enrichment analysis, gene expression', 38, 28994825, 107, 'https://github.com/MaayanLab/clustergrammer', 'https://www.youtube.com/watch?v=8MgvyeroW98', 'clustergrammer', 'visualization'),
('Harmonizome', 'http://labs.icahn.mssm.edu/maayanlab/wp-content/uploads/sites/75/2014/10/harmonizome.png', 'https://amp.pharm.mssm.edu/Harmonizome/', 'https://amp.pharm.mssm.edu/Harmonizome/documentation', 'https://www.ncbi.nlm.nih.gov/pubmed/27374120', 'datasets, database, visualization, machine learning, genes, proteins, LINCS', 153, 27374120, 22, 'https://github.com/MaayanLab/harmonizome', 'https://www.youtube.com/watch?v=ZyOIQwEh_58', 'harmonizome', 'visualization'),
('Datasets2Tools', 'http://labs.icahn.mssm.edu/maayanlab/wp-content/uploads/sites/75/2014/10/D2T-150x150.png', 'https://amp.pharm.mssm.edu/datasets2tools/', 'https://amp.pharm.mssm.edu/datasets2tools/help', 'https://www.ncbi.nlm.nih.gov/pubmed/29485625', 'database, datasets, canned analyses, interoperability, LINCS', 23, 29485625, 22, 'https://github.com/MaayanLab/datasets2tools', 'https://www.youtube.com/watch?v=cEYXVpfani0', 'datasets2tools', 'databases'),
('Genes2Networks', 'http://labs.icahn.mssm.edu/maayanlab/wp-content/uploads/sites/75/2014/10/genes2networks.png', 'https://amp.pharm.mssm.edu/G2N/', '', 'https://www.ncbi.nlm.nih.gov/pubmed/17916244', 'command line, datasets, protein-protein interaction, network, database, interoperability', 42, 17916244, 6, 'https://github.com/MaayanLab/Genes2Networks', 'https://www.youtube.com/watch?v=HhCQRWl5T3M','genes2networks', 'databases'),
('ESCAPE', 'http://labs.icahn.mssm.edu/maayanlab/wp-content/uploads/sites/75/2014/10/ESCAPE-icon.png', '', '', 'https://www.ncbi.nlm.nih.gov/pubmed/23794736', 'database, proteomics, visualization, networks', 26, 23794736, 9, '', '', 'escape', 'databases'),
('X2K Web', 'http://labs.icahn.mssm.edu/maayanlab/wp-content/uploads/sites/75/2014/10/x2kweb_logo-300x83.png', 'https://amp.pharm.mssm.edu/X2K/', 'https://amp.pharm.mssm.edu/X2K/', 'https://www.ncbi.nlm.nih.gov/pubmed/29800326', 'gene expression, gene signature, cell signaling pathway, enrichment analysis, transcription factors, protein-protein interactions, command line', 33, 29800326, 7, 'https://github.com/MaayanLab/x2k_web', 'https://www.youtube.com/watch?v=V8G2EuYl7os', 'x2kweb', 'command line'),
('Expression2Kinases', 'http://labs.icahn.mssm.edu/maayanlab/wp-content/uploads/sites/75/2014/10/X2K_icon.png', 'https://amp.pharm.mssm.edu/X2K/', 'https://amp.pharm.mssm.edu/X2K/', 'https://www.ncbi.nlm.nih.gov/pubmed/29800326', 'gene expression, gene signature, cell signaling pathway, enrichment analysis, transcription factors, protein-protein interactions, command line', 33, 29800326, 7, 'https://github.com/MaayanLab/x2k_web', 'https://www.youtube.com/watch?v=V8G2EuYl7os', 'expression2kinases', 'command line'),
('Sig2BioPAX', 'http://labs.icahn.mssm.edu/maayanlab/wp-content/uploads/sites/75/2014/10/sig2biopax.png', 'https://code.google.com/archive/p/sig2biopax/', '', 'https://www.ncbi.nlm.nih.gov/pubmed/21418653', 'command line, networks', 19, 21418653, NULL, '', '', 'sig2biopax', 'command line'),
('Enrichr', 'http://labs.icahn.mssm.edu/maayanlab/wp-content/uploads/sites/75/2014/10/enrichr.png', 'https://amp.pharm.mssm.edu/Enrichr/', 'https://amp.pharm.mssm.edu/Enrichr/help#basics', 'https://www.ncbi.nlm.nih.gov/pubmed/27374120', 'gene sets, library, visualization, signatures, enrichment analysis, LINCS', 54, 23586463, 21, 'https://github.com/MaayanLab/enrichr', 'https://www.youtube.com/watch?v=HfUZdNJ9a3A', 'enrichr', 'lincs'),
('GEN3VA', 'http://labs.icahn.mssm.edu/maayanlab/wp-content/uploads/sites/75/2014/10/gen3va_logo-150x150.png', 'https://amp.pharm.mssm.edu/gen3va/', 'https://amp.pharm.mssm.edu/gen3va/documentation', 'https://www.ncbi.nlm.nih.gov/pubmed/27846806', 'gene expression, heatmap, enrichment analysis, small molecules, signatures, LINCS', 41, 27846806, 8, 'https://github.com/MaayanLab/gen3va', '', 'gen3va', 'lincs'),
('CREEDS', 'http://labs.icahn.mssm.edu/maayanlab/wp-content/uploads/sites/75/2014/10/creeds_logo.fw_-150x150.png', 'https://amp.pharm.mssm.edu/CREEDS/', 'https://amp.pharm.mssm.edu/CREEDS/#help/#api-doc', 'https://www.ncbi.nlm.nih.gov/pubmed/27667448', 'gene expression, signatures, visualization, LINCS', 78, 27667448, 41, 'https://github.com/MaayanLab/creeds', 'https://www.youtube.com/watch?list=PLfq4yYrYksVhaor4HRZRt174F1WFcFDFN&v=y5QS81nKijM', 'creeds', 'lincs'),
('SEP L1000', 'http://labs.icahn.mssm.edu/maayanlab/wp-content/uploads/sites/75/2014/10/sep.png', 'https://maayanlab.net/SEP-L1000/', 'https://maayanlab.net/SEP-L1000/', 'https://www.ncbi.nlm.nih.gov/pubmed/27153606', 'LINCS, IDG, machine learning, gene expression', 40, 27153606, 19, 'https://github.com/MaayanLab/SEP-L1000', '', 'sepl1000', 'idg'),
('Datasets2Tools', 'http://labs.icahn.mssm.edu/maayanlab/wp-content/uploads/sites/75/2014/10/D2T-150x150.png', 'https://amp.pharm.mssm.edu/datasets2tools/', 'https://amp.pharm.mssm.edu/datasets2tools/help', 'https://www.ncbi.nlm.nih.gov/pubmed/29485625', 'database, datasets, canned analyses, interoperability, LINCS', 23, 29485625, 22, 'https://github.com/MaayanLab/datasets2tools', 'https://www.youtube.com/watch?v=cEYXVpfani0', 'datasets2tools', 'interoperability'),
('GATE', 'http://labs.icahn.mssm.edu/maayanlab/wp-content/uploads/sites/75/2014/10/gate.png', '', '', 'https://www.ncbi.nlm.nih.gov/pubmed/19892805', 'visualization, interoperability', 10, 19892805, NULL, '', '', 'gate', 'interoperability')

;

